version: "3.9"


services:
  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
    command: celery -A app worker -l INFO
    volumes:
      - ./app:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - app
      
  app:
    build:
      context: .

    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django




volumes:
    postgres_data: