# Generated by Django 4.0.8 on 2023-03-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_filmweb_nick'),
        ('core', '0002_alter_userprofile_last_watched_and_more'),
    ]

    operations = [
    ]
