# Generated by Django 4.0.8 on 2022-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filmweb_nick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
