# Generated by Django 4.0.8 on 2022-10-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='posts',
            new_name='post',
        ),
    ]
