# Generated by Django 4.0.8 on 2022-10-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_posts_userprofile_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='post',
            new_name='posts',
        ),
    ]
