# Generated by Django 4.0.8 on 2022-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_post_userprofile_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(to='core.post'),
        ),
    ]
